#define CONFIG_WL_SECTOR_SIZE_512 1
#define CONFIG_WL_SECTOR_SIZE 512
#define CONFIG_WL_SECTOR_MODE 1
#define CONFIG_WL_SECTOR_MODE_SAFE 1
#define CONFIG_FATFS_CODEPAGE_437 1
#define CONFIG_FATFS_CODEPAGE 437
#define CONFIG_FATFS_LFN_HEAP 1
#define CONFIG_FATFS_MAX_LFN 127
