// MicroPython version info
#define MICROPY_GIT_TAG "ESP32_LoBo_v3.1.17"
#define MICROPY_GIT_HASH "gdaa8cfa8"
#define MICROPY_BUILD_DATE "2017-02-05"
#define MICROPY_VERSION_MAJOR (3)
#define MICROPY_VERSION_MINOR (1)
#define MICROPY_VERSION_MICRO (17)
#define MICROPY_VERSION_STRING "3.1.17"
