// MicroPython version info
#define MICROPY_GIT_TAG "ESP32_LoBo_v3.1.9"
#define MICROPY_GIT_HASH "g2ddee729"
#define MICROPY_BUILD_DATE "2017-01-21"
#define MICROPY_VERSION_MAJOR (3)
#define MICROPY_VERSION_MINOR (1)
#define MICROPY_VERSION_MICRO (9)
#define MICROPY_VERSION_STRING "3.1.9"
