// MicroPython version info
#define MICROPY_GIT_TAG "ESP32_LoBo_v3.1.0"
#define MICROPY_GIT_HASH "g1837a034"
#define MICROPY_BUILD_DATE "2017-01-03"
#define MICROPY_VERSION_MAJOR (3)
#define MICROPY_VERSION_MINOR (1)
#define MICROPY_VERSION_MICRO (0)
#define MICROPY_VERSION_STRING "3.1.0"
